[pytest]
markers =
    ui: UI-тесты для Aviasales
    api: API-тесты для Aviasales
    critical: Критические тесты
    normal: Обычные тесты

addopts = -v --alluredir=allure-results
testpaths = .
python_files = test_*.py
python_classes = Test*
python_functions = test_*